### ISSUE TITLE
Exception retrieving machine info: 'data'

### ISSUE THREAD

**Issue by mrvautin** [rccoleman/lamarzocco#23]
My machine suddenly stopped working and my logs are showing the error below. I've removed and re-added but can't get it working. When I try add back my `Config>Integration` I get a generic `Unknown error occurred`.

Any clues?

Logger: lmdirect.connection
Source: /usr/local/lib/python3.9/site-packages/lmdirect/connection.py:532
First occurred: 9:43:51 (1 occurrences)
Last logged: 9:43:51

```
Version: core-2021.8.4
Newest Version: core-2021.8.4
```

```
Exception retrieving machine info: 'data'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/lmdirect/connection.py", line 160, in _connect
    self._machine_info = await self.retrieve_machine_info(
  File "/usr/local/lib/python3.9/site-packages/lmdirect/connection.py", line 111, in retrieve_machine_info
    fleet = cust_info.json()["data"]["fleet"][0]
KeyError: 'data'
```

**Comment by rccoleman** [comment]
Yes, the issue is that the `httpx` package was updated to 0.18.2 in HA to address an issue with the Denon integration and the latest release of `authlib` hasn't yet been updated to accommodate it.  The fix has been checked into the mainline, but I'm still waiting for a release that includes it.

I've been working around it by manually downgrading `httpx` to 0.18.1 in HA and I don't see any ill effects, so you could try doing the same.  One fairly easy way to do that is to download [this zip file](https://github.com/encode/httpx/archive/refs/tags/0.18.1.zip) from the repo and copy the `httpx` directory into your config directory.  That will cause HA to preferentially use the 0.18.1 version.  If you do that, just make sure to remember that you did it so that you can remove it when there's a new `authlib` release that works with `httpx` 0.18.2.

Sorry about this - I was hoping that a new `authlib` release would be quick in coming, but it's taking a while.

**Comment by mrvautin** [comment]
Awesome. That fixed it. I'm glad it wasn't just me.

**Comment by mitchej** [comment]
Thanks @rccoleman that's a great workaround. BTW, this is my favourite integration by a long shot - awesome work!
