### ISSUE TITLE
Issue w/ httpx 0.19.0 oauth and 

### ISSUE THREAD

**Issue by mikelikespie** [rccoleman/lamarzocco#24]
Hi, was trying to get this working w/ my new GS3 and I was having issues. I tracked it down to OAuth headers not working w/ newer version of httpx (https://github.com/lepture/authlib/issues/377 seems to be the culprit). However, it seems as if current HA depends on this version.

**Comment by rccoleman** [comment]
Yes, you're correct, and I mentioned in a recent issue: https://github.com/rccoleman/lamarzocco/issues/23.  The issue is with authlib, and as soon as there's a new release that includes that change, it will be picked up automatically.  In the meantime, I have seen no compatibility issues with `httpx==0.18.1`, and you're welcome to try the workaround that I mentioned in that issue ([here](https://github.com/rccoleman/lamarzocco/issues/23#issuecomment-894882845)).

**Comment by mikelikespie** [comment]
@rccoleman Thanks! That worked! Also thanks for your work on the integrations. Excited to be able to control it from HA
